version: '2'
services:
  tomcat-1:  
    image: tomcat1
    ports: 
      - "9001:8080"
    container_name: app1
    volumes:
      - ./logs/:/usr/local/tomcat/logs
    networks: 
      my-network: 
         ipv4_address: 10.0.1.2
  tomcat-2:
    image: tomcat2
    ports: 
     - "9002:8080"
    container_name: app2   
    volumes: 
     - ./logs/:/usr/local/tomcat/logs2
    networks: 
      my-network: 
         ipv4_address: 10.0.1.3
  nginx: 
    image: nginx-main  
    ports:
      - "80:80"
    container_name: balancer
    networks: 
      my-network:
         ipv4_address: 10.0.1.4
 
networks: 
  my-network:
     ipam: 
       driver: default 
       config: 
          - subnet: 10.0.1.0/24 